### ISSUE TITLE
BackPressDispatcher callback wrong order

### ISSUE THREAD

**Issue by steelahhh** [badoo/Decompose#11]
Callback registered in a component gets called only after the system `onBackPressed`

Also nested routers stopped working, which might be related to this issue

Looks like a regression from 0.1.0, because the same code works on that version

**Comment by arkivanov** [comment]
Hello @steelahhh! Thanks for the report. I could only reproduce the issue with nested routers. This is broken indeed and I will fix it. 

But I could not reproduce the issue with call order. Activity `onBackPressed` is called before components, and I believe this is by design. Decompose hooks to AndroidX `OnBackPressedDispatcher`, which is called from inside Activity `onBackPressed`.

**Comment by steelahhh** [comment]
Found a bit more exact case when it happens: 

In the todo sample app, whatever is in `backPressedDispatcher.register` in the `TodoEditImpl` doesn't get executed when doing `unregister` in `onDestroy`. But without `unregister`ing it does get called, but only after navigating back. 

Also, it does seem to be called when it's in the topmost item in the stack (i.e. pressing back button calls system `onBackPressed`)

And it works on 0.1.0 – callback gets called before the system one

**Comment by arkivanov** [comment]
Thanks! I will fix it.

**Comment by arkivanov** [comment]
So both cases (nested routers and "whatever is in `backPressedDispatcher.register` in the `TodoEditImpl` doesn't get executed when doing `unregister` in `onDestroy`") are because of the wrong iteration order of the registered handlers. This regression was introduced in version `0.1.1`. This is now fixed via 9103261ccfdb33e9c64fce3eb459d793e45a4968.

The case "without `unregister`ing it does get called, but only after navigating back" is because of a memory leak, which was there for a long time actually. This is now fixed via fcbfa4bb00676ce2269d4f549b47abace65e2392. So there is no need to `unregister` handlers, unless you really need.

**Comment by arkivanov** [comment]
Version `0.1.2` is published.
