### ISSUE TITLE
Dependency Updates Gradle Plugin fails to determine the version of Decompose

### ISSUE THREAD

**Issue by moffpage** [badoo/Decompose#152]
Dependency Updates Gradle Plugin (link: https://github.com/ben-manes/gradle-versions-plugin) fails to determine the version of Decompose even with explicit indication (I used the current recent 0.2.4) like this:

```
implementation(dependencyNotation = "com.arkivanov.decompose:decompose:0.2.4")
implementation(dependencyNotation = "com.arkivanov.decompose:extensions-compose-jetpack:0.2.4")

```

I just add this block:

```
plugins {
  id("com.github.ben-manes.versions") version "0.38.0"
}
```

inside root project's **build.gradle.kts** file and providing implementations how it should be done.

You can easily create the project by yourself, after all of that run `gradle dependencyUpdates` with `--info` optionally to get more details

**Comment by arkivanov** [comment]
I could not reproduce the error with the private project provided by you. Perhaps the issue is MacOS-specific, and I am using Ubuntu. Overall this error looks related to the plugin itself. I recommend to file an issue in the plugin's repository, they already have few similar issues closed.

At the moment I can't do anything with this issue.
