### ISSUE TITLE
Nullable Value/MutableValue

### ISSUE THREAD

**Issue by Tommyten** [badoo/Decompose#258]
Hello, thanks for this great Framework!
Is there any reason why the Value/MutableValue Classes do not accept nullable Types?
There are some usecases where having null wrapped in a MutableValue would help.

**Comment by arkivanov** [comment]
@Tommyten this is by design, due to how generics are exported to Swift. If we define it as `Value<T>`, then a non-null type (e.g. `Value<String>`) will be still nullable in Swift.

For the same reason they both are classes, and not interfaces. Because generics for interface can not be exported to Swift.

**Comment by arkivanov** [comment]
You can workaround nullable types by using something like `data class Optional<T : Any>(val value: T?)`.

**Comment by Tommyten** [comment]
Alright, thank you :)
